### ISSUE TITLE
Create dashboard

### ISSUE THREAD

**Issue by dewarian** [sjagoori/bloom#16]
Create a navigation throughout the application.

![Untitled](https://user-images.githubusercontent.com/13199349/119819807-0f6b0600-bef1-11eb-9d07-e3ba3f3b608d.png)
)

**Comment by dewarian** [comment]
@sjagoori Currently Logging in navigates the user to a page called dashboard. 
Should we move this to another page such as themes or chats?

Currently the application not the design has something that resembles a dashboard...

**Comment by sjagoori** [comment]
dashboard should contain all 4 pages, to that the user can switch between them using useState

**Comment by sjagoori** [comment]
https://github.com/sjagoori/bloom/pull/34/commits/a9ad9327468a2b67064f7969e68d2e3987563e8b
